# Generated by Django 4.1 on 2023-11-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=225)),
                ('added_by', models.IntegerField()),
                ('approved_status', models.IntegerField(max_length=1)),
                ('description', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
