# Generated by Django 4.1 on 2023-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='approved_status',
            field=models.IntegerField(),
        ),
    ]
