# Generated by Django 4.1 on 2023-12-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_options_answer_alter_question_approved_status'),
        ('startquiz', '0002_alter_result_status_alter_result_total_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.options'),
        ),
    ]
