# Generated by Django 4.1 on 2023-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_questions', models.IntegerField()),
                ('max_marks', models.FloatField()),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
