# Generated by Django 4.1 on 2023-12-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='max_marks',
            new_name='mark_per_questions',
        ),
    ]
