# Generated by Django 4.1 on 2023-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_rename_max_marks_setting_mark_per_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='time_per_questions',
            field=models.IntegerField(default=1),
        ),
    ]
