# Generated by Django 4.1 on 2023-12-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_setting_time_per_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='pass_percentage',
            field=models.IntegerField(default=70),
        ),
    ]
